---
- hosts: localhost
  become: yes
  gather_facts: yes
  vars_files:
    - vars/main.yml

  tasks:

    - name: Install to /usr/local/update-on-boot/
      copy:
        src: ../update-on-boot
        dest: /usr/local/
        owner: root
        group: root
        mode: '0640'
        directory_mode: '0750'

    - name: Set script executable
      file:
        path: /usr/local/update-on-boot/files/updatecheck.archlinux.sh
        owner: root
        group: root
        mode: '0550'
        
    - name: Install update-on-boot.service
      copy:
        src: files/update-on-boot.service
        dest: /etc/systemd/system/
        mode: '640'

    - name: Enable update-on-boot.service
      systemd:
        name: update-on-boot
        enabled: yes
