---
- hosts: localhost
  become: yes
  gather_facts: yes
  vars_files:
    - vars/main.yml

  tasks:

    - name: Get all missing updates
      script: ../files/updatecheck.archlinux.sh
      register: scriptoutput
      args:
        executable: bash

    - name: Send mail
      mail:
        to: "{{ mailadress }}"
        subject: "Updates on {{ ansible_hostname }}"
        body: "'{{ scriptoutput.stdout }}'"

    - name: These updates will be installed
      debug: var=scriptoutput.stdout_lines

    - name: Running full systemupdate
      pacman:
        update_cache: yes
        upgrade: yes
      when: ansible_distribution == "Archlinux"

    - name: Check if reboot requested
      stat:
        path: /tmp/update-on-boot.reboot
      register: reboot_required

    - name: Prevent reboot-loop
      file:
        path: /tmp/update-on-boot.reboot
        state: absent

    - name: Reboot triggered
      command: reboot
      when: reboot_required.stat.exists == True
